import { registerAdapter } from './runner';
import { csvMembersAdapter } from './adapters/csv-members';
import { csvClubsAdapter } from './adapters/csv-clubs';
import { csvOfficersAdapter } from './adapters/csv-officers';
import { csvAttendanceAdapter } from './adapters/csv-attendance';
import { csvDonationsAdapter } from './adapters/csv-donations';
import { csvActivitiesAdapter } from './adapters/csv-activities';
import { csvEventsAdapter } from './adapters/csv-events';
import { csvDistrictsAdapter } from './adapters/csv-districts';
import { excelDistrictsAdapter } from './adapters/excel-districts';
import { restMembersAdapter } from './adapters/rest-members';
import { restClubsAdapter } from './adapters/rest-clubs';
import { restOfficersAdapter } from './adapters/rest-officers';

registerAdapter(csvMembersAdapter);
registerAdapter(csvClubsAdapter);
registerAdapter(csvOfficersAdapter);
registerAdapter(csvAttendanceAdapter);
registerAdapter(csvDonationsAdapter);
registerAdapter(csvActivitiesAdapter);
registerAdapter(csvEventsAdapter);
registerAdapter(csvDistrictsAdapter);
registerAdapter(excelDistrictsAdapter);
registerAdapter(restMembersAdapter);
registerAdapter(restClubsAdapter);
registerAdapter(restOfficersAdapter);

export * from './types';
export * from './runner';
export { csvToTable, parseCsv } from './csv';
